server:
  port: 8082

  servlet:
    context-path: /kafka
    
spring:
  application:
    name: kafka
    
eureka:
  client:
    register-with-eureka: true       # restister to eureka
    fetch-registry: true    
    service-url:
      defaultZone: http://localhost:8761/eureka/    
      
      
      
      