server:
  port: 8761

spring:
  application:
    name: service-registry
  
eureka:
  client:
    register-with-eureka: false       # dont restister itself to eureka
    fetch-registry: false
    service-url:
      #defaultZone: http://localhost:8761/eureka/ 
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE} 
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always    
    